excluded:
  - InternetArchiveKitTests
  - InternetArchiveKitExample
  - InternetArchiveKitExampleMacOS
type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 80
line_length:
  error: 120
