language: swift
xcode_project: InternetArchiveKit.xcodeproj
xcode_scheme: InternetArchiveKit
xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  homebrew:
    brewfile: true
